# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 20:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberinfo',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='memberinfo',
            name='feet',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='memberinfo',
            name='inches',
            field=models.IntegerField(default=11),
        ),
        migrations.AddField(
            model_name='memberinfo',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memberinfo',
            name='weight',
            field=models.IntegerField(default=160),
        ),
    ]
